name: SonarCloud Analysis

on:
  push:
    branches:
      - main
      - devel
  pull_request:
    branches:
      - main
      - devel

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage pytest pytest-django

      - name: Create .env file
        run: |
          cat <<EOF > .env
          GITHUB_CLIENT_ID='test_client_id'
          GITHUB_CLIENT_SECRET='test_client_secret'
          GITHUB_REDIRECT_URI='http://localhost:8000/callback/'
          DB_NAME=test_db
          DB_USER=test_user
          DB_PASSWORD=test_pass
          DB_HOST=localhost
          DB_PORT=5432
          EOF

      - name: Run tests with coverage
        run: |
          coverage run --source='.' manage.py test
          coverage xml
        continue-on-error: true

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
